Prokaryotes:
  - Bacteria
  - Archaea
Cyanobacteria:
  - Cyanobacteria
Chlorophyta:
  - Chlorophyta
Dinoflagellata:
  - Dinoflagellata
Diatoms:
  - Bacillariophyta
  - Diatomea
Pelagophyceae:
  - Pelagophyceae
Haptophyta:
  - Haptophyta
Ciliophora:
  - Ciliophora
Ochrophyta:
  - Ochrophyta
Metazoa:
  - Metazoa
